name = "skylogged"
author = "Vercte"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "908a12e796d31e109cdcaeb85cc9fde1532d625e82782a8eeb6fe544afe35698"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21"]
