name = "skylogged"
author = "Vercte"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab9c48b05879dc04ff3c1f8a582fc8c56908c6ae12d81871292a9d0678bb140f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
