name = "airlogged"
author = "Vercte"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0260e4a5026503ce75229cf13808aaa2e2f7b6ef9380b79f32aee4c7d0bf8c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
